baseURL: http://aayushmau5.github.io/
languageCode: en-us
title: Blogs by aayushmau5
theme: "PaperMod"

enableRobotsTXT: true

minify:
  minifyOutput: true

params:
  env: production
  author: "aayushmau5"
  description: "blogs by Aayush Kumar Sahu"
  images: ["/cover.png"]
  keywords: ["aayushmau5", "blog"]
  defaultTheme: dark

  ShowReadingTime: true
  ShowPostNavLinks: true
  comments: false
  ShowBreadCrumbs: true
  hideSummary: true
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true

  # profileMode:
  #   enabled: false
  #   title: Aayush Kumar Sahu
  #   subtitle: "A web developer and an open-source enthusiast"
  #   imageUrl: "https://avatars.githubusercontent.com/u/54525741?v=4"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image

  homeInfoParams:
    Title: "Hi \U0001F44B"
    Content: Just sharing what I learn

  socialIcons:
    - name: twitter
      url: "https://twitter.com/aayushmau5"
    - name: linkedin
      url: "https://in.linkedin.com/in/aayushmau5"
    - name: github
      url: "https://github.com/aayushmau5"

  cover:
    hiddenInList: true

  assets:
    disableHLJS: true

menu:
  main:
    # - identifier: posts
    #   name: Posts
    #   url: /posts/
    #   weight: 5
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: about
      name: About Me
      url: /about/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10

markup:
  highlight:
    # noClasses: false
    # pygmentsUseClasses: true
    lineNos: true
    guessSyntax: true
    codeFences: true
    style: paraiso-dark

outputs:
  home:
    - HTML
    - RSS
    - JSON
